### ISSUE TITLE
Resulting images are all 300x150 pixels wide

### ISSUE THREAD

**Issue by jhohlfeld** [kyo-ago/copy-base64#1]
Great minimalistic tool! I have the problem though, that per default, all images are captured at 300x150. Is there a way to fix this?

**Comment by kyo-ago** [comment]
Thank you for the issue.

Fixed this problem in version 0.0.3.
(Version 0.0.3 is released now.)

Please check for new version.
https://chrome.google.com/webstore/detail/copy-base64/obeffifkdkfbpodhaoelcjdljgiapjnl/details
